repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: requirements-txt-fixer

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    name: black

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort

- repo: local
  hooks:
  - id: cairo-format
    name: cairo-format
    language: system
    entry: cairo-format -i
    files: \.cairo$
